POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMTMiLCJpZCI6IjY5NDVkNDAwMTE4NGRiNGI4NTc2Yjk2MCIsImlhdCI6MTc2NjE4NTQwNiwiZXhwIjoxNzY2MTg5MDA2fQ.ArpOhEZD02AdxZxjPXsAzxrSxSP0FUZoMF9c8FCj3nc

{
    "title": "Testiblogi13",
    "author": "Testi Käyttäjä",
    "url": "example.com",
    "likes": 9000,
    "userId": "6945d4001184db4b8576b960"

}